name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - run: pip install uv
    - run: pwd
    - run: |
        uv cache dir
        uv pip install attrs --system
      env:
        UV_CACHE_DIR: /tmp/uv-cache
